//! The composite spend root `b = b_owner + b_gate`, and the one-time key and
//! key image derived from it.

use core::{fmt, marker::PhantomData};

use curve25519_dalek::{
    constants::RISTRETTO_BASEPOINT_POINT, ristretto::RistrettoPoint, scalar::Scalar,
};
use mc_crypto_keys::{RistrettoPrivate, RistrettoPublic};
use mc_crypto_ring_signature::KeyImage;
use rand_chacha::ChaCha20Rng;
use rand_core::{CryptoRng, RngCore, SeedableRng};
use zeroize::Zeroizing;

use crate::{
    ceremony::{AuditedAddress, CeremonyId, ComponentReveal, Parties},
    cohort::{random_scalar, Cohort},
    control::{ControlDomain, Gates, Owners},
    derive::{hash_to_point, hash_to_scalar, subaddress_offset},
    error::Result,
};

/// Where a [`CompositeSpend`]'s root came from.
///
/// Recorded on the value rather than left to the caller's memory because the
/// two are not interchangeable and nothing else about the type distinguishes
/// them: a simulated root was generated by a single process that could spend it
/// alone, and a ceremony root reached this type through
/// [`audit`](crate::audit). A release path can refuse
/// [`Provenance::Simulated`] with one match arm.
///
/// **This records a ROUTE, not a history.** `Ceremony` says the value was built
/// from an [`AuditedAddress`](crate::AuditedAddress), which only
/// [`audit_address`](crate::audit_address) issues. It does not say a distributed
/// ceremony took place: an artifact produced by a dealer that generated every
/// share audits, and receives this tag --
/// `tests/forgery.rs::a_dealt_owner_cohort_passes_the_audit_and_the_release_gate`
/// carries one all the way to a published address.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Provenance {
    /// [`CompositeSpend::simulate`]. A TRUSTED DEALER generated both component
    /// secrets and every share in one process.
    Simulated,
    /// [`CompositeSpend::from_ceremony`], with the audited composition that
    /// produced the root.
    ///
    /// An earlier version of this line said "no process held both components,
    /// and the shares live with the participants that generated them". Neither
    /// clause is established by anything: a single process can run both DKGs
    /// (`tests/attribution.rs` performs it), and a dealer can generate every
    /// share and keep it (`tests/forgery.rs` performs that). What this variant
    /// establishes is that the root came through [`audit`](crate::audit) under
    /// identity keys the caller supplied.
    Ceremony(CeremonyId),
}

/// How to deal one cohort: who is on it and how many of them are needed.
///
/// Parameterised by the control domain, so an owner spec and a gate spec are
/// different types. Handing [`CompositeSpend::simulate`] its two arguments the
/// wrong way round is a compile error rather than a scheme that quietly
/// degrades to one cohort:
///
/// ```compile_fail
/// use two_cohort::{CohortSpec, CompositeSpend, Gates, Owners};
///
/// let owners = CohortSpec::<Owners>::sequential(2, 3);
/// let gates = CohortSpec::<Gates>::sequential(2, 3);
/// // the two arguments the wrong way round
/// let _ = CompositeSpend::simulate_from_seed(0, &gates, &owners, 0);
/// ```
///
/// Nor can both halves be drawn from the same domain, which is what "two
/// cohorts" degenerates into when the separation is only a naming convention:
///
/// ```compile_fail
/// use two_cohort::{CohortSpec, CompositeSpend, Owners};
///
/// let a = CohortSpec::<Owners>::sequential(2, 3);
/// let b = CohortSpec::<Owners>::sequential(2, 3);
/// let _ = CompositeSpend::simulate_from_seed(0, &a, &b, 0);
/// ```
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CohortSpec<C> {
    threshold: usize,
    ids: Vec<u64>,
    domain: PhantomData<C>,
}

impl<C: ControlDomain> CohortSpec<C> {
    /// The first `n` ids of this domain's band.
    pub fn sequential(threshold: usize, n: usize) -> Self {
        CohortSpec::with_ids(threshold, &(0..n as u64).map(C::nth).collect::<Vec<_>>())
    }

    /// An explicit roster.
    ///
    /// The ids are absolute -- use [`ControlDomain::nth`] to name them by
    /// position. They are not validated here: a spec is inert data, and the
    /// rejection belongs where the cohort is actually dealt, so that one error
    /// path covers specs built by any route.
    pub fn with_ids(threshold: usize, ids: &[u64]) -> Self {
        CohortSpec {
            threshold,
            ids: ids.to_vec(),
            domain: PhantomData,
        }
    }

    pub fn name(&self) -> &'static str {
        C::NAME
    }

    pub fn threshold(&self) -> usize {
        self.threshold
    }

    pub fn ids(&self) -> &[u64] {
        &self.ids
    }
}

/// The per-participant pieces of one key image, before anything is summed.
///
/// A production signer combines these in the group and never forms the scalar
/// they correspond to. This crate exposes them so such a signer can be written
/// against a shape that is already correct; it does not implement one.
#[derive(Clone, Debug)]
pub struct KeyImageTerms {
    /// `common * Hp(P)`. Derived from the view key, so it belongs to whoever
    /// runs the view service and to neither cohort.
    pub view_term: RistrettoPoint,
    pub owner_terms: Vec<(u64, RistrettoPoint)>,
    pub gate_terms: Vec<(u64, RistrettoPoint)>,
}

impl KeyImageTerms {
    /// The assembled image point.
    pub fn sum(&self) -> RistrettoPoint {
        let owners: RistrettoPoint = self.owner_terms.iter().map(|(_, p)| p).sum();
        let gates: RistrettoPoint = self.gate_terms.iter().map(|(_, p)| p).sum();
        self.view_term + owners + gates
    }

    /// The assembled image in the form consensus compares.
    pub fn key_image(&self) -> KeyImage {
        KeyImage {
            point: self.sum().compress(),
        }
    }
}

/// One output paid to a subaddress of a composite two-cohort spend root.
///
/// ```text
///     b        = b_owner + b_gate           composite spend root
///     b_owner  shared k-of-n across OWNERS  (own roster, own threshold)
///     b_gate   shared g-of-m across GATES   (own roster, own threshold)
///     d_i      = b + Hs(a || i)             subaddress spend key
///     x        = Hs(a * R) + d_i            one-time key for this output
///     I        = x * Hp(P)                  key image
/// ```
///
/// The property the whole scheme rests on: `I` must be identical for every
/// (owner-subset x gate-subset) pair. An image that varied with the signing
/// subset would let one output be spent twice under two different images, and
/// consensus deduplicates on the image.
pub struct CompositeSpend {
    /// Private so the pair cannot be reassigned after construction. The
    /// disjointness of the two rosters is established once, at
    /// [`CompositeSpend::simulate`], and a `pub` field would let a caller
    /// replace one cohort with a clone of the other afterwards.
    owners: Cohort,
    gates: Cohort,
    provenance: Provenance,
    /// The two organisations whose endorsements the audit behind this spend was
    /// checked against, for a ceremony root; `None` for a simulated one.
    ///
    /// Carried forward rather than left behind because
    /// [`audit`](crate::audit) checks the commitments against keys its CALLER
    /// supplied, and a release path that only sees a `CompositeSpend` would
    /// otherwise have no way to know which keys those were. A key audited under
    /// an attacker's pair of "organisations" is as well-formed as one audited
    /// under the real pair; the difference is only visible if the pair travels
    /// with the value. See
    /// [`production::authorize_release`](crate::production::authorize_release).
    endorsers: Option<Parties>,
    view_private: RistrettoPrivate,
    subaddress_index: u64,
    spend_public: RistrettoPublic,
    tx_public: RistrettoPublic,
    target: RistrettoPublic,
    /// `Hs(a * R) + Hs(a || i)`: everything in the one-time key that comes
    /// from the view key. Neither cohort secret appears in it.
    common: Zeroizing<Scalar>,
}

impl CompositeSpend {
    /// Deal both cohorts over a fresh composite root and pay an output to
    /// subaddress `subaddress_index` of it.
    ///
    /// This is a TRUSTED DEALER: the two component secrets and the view key
    /// are generated here, in this process, and the shares never leave it.
    /// See the crate-level limitations.
    pub fn simulate<R: RngCore + CryptoRng>(
        owners: &CohortSpec<Owners>,
        gates: &CohortSpec<Gates>,
        subaddress_index: u64,
        rng: &mut R,
    ) -> Result<CompositeSpend> {
        let view = Zeroizing::new(random_scalar(rng));
        let b_owner = Zeroizing::new(random_scalar(rng));
        let b_gate = Zeroizing::new(random_scalar(rng));
        // The sender's per-output secret. Not ours -- modelled only so there is
        // a real output to spend.
        let tx_private = Zeroizing::new(random_scalar(rng));

        let owner_cohort =
            Cohort::deal_in::<Owners, _>(&b_owner, owners.threshold, &owners.ids, rng)?;
        let gate_cohort = Cohort::deal_in::<Gates, _>(&b_gate, gates.threshold, &gates.ids, rng)?;

        let root = *b_owner * RISTRETTO_BASEPOINT_POINT + *b_gate * RISTRETTO_BASEPOINT_POINT;
        Ok(Self::from_parts(
            owner_cohort,
            gate_cohort,
            Provenance::Simulated,
            &view,
            &root,
            subaddress_index,
            &tx_private,
        ))
    }

    /// Deterministic convenience wrapper over [`CompositeSpend::simulate`].
    ///
    /// Seeded so failures reproduce; do not mistake it for key generation.
    pub fn simulate_from_seed(
        seed: u64,
        owners: &CohortSpec<Owners>,
        gates: &CohortSpec<Gates>,
        subaddress_index: u64,
    ) -> Result<CompositeSpend> {
        let mut rng = ChaCha20Rng::seed_from_u64(seed);
        CompositeSpend::simulate(owners, gates, subaddress_index, &mut rng)
    }

    fn from_parts(
        owners: Cohort,
        gates: Cohort,
        provenance: Provenance,
        view: &Scalar,
        root: &RistrettoPoint,
        subaddress_index: u64,
        tx_private: &Scalar,
    ) -> CompositeSpend {
        let g = RISTRETTO_BASEPOINT_POINT;
        let offset = Zeroizing::new(subaddress_offset(view, subaddress_index));

        // D_i = B + Hs(a || i) * G ; C_i = a * D_i
        let spend_public = RistrettoPublic::from(root + *offset * g);
        let view_public = RistrettoPublic::from(view * spend_public.as_ref());

        // R = r * D_i ; P = Hs(r * C_i) * G + D_i
        let tx_public = RistrettoPublic::from(tx_private * spend_public.as_ref());
        let target = RistrettoPublic::from(
            hash_to_scalar(tx_private * view_public.as_ref()) * g + spend_public.as_ref(),
        );

        let common = Zeroizing::new(hash_to_scalar(view * tx_public.as_ref()) + *offset);

        CompositeSpend {
            owners,
            gates,
            provenance,
            // `from_parts` is the DEALER's constructor -- `simulate` is its only
            // caller -- and a dealt root was endorsed by nobody. `from_ceremony`
            // builds its value directly and fills this in from the audit.
            endorsers: None,
            view_private: RistrettoPrivate::from(*view),
            subaddress_index,
            spend_public,
            tx_public,
            target,
            common,
        }
    }

    /// Build a spend for an output paid to an AUDITED composite address.
    ///
    /// This is the production constructor, and the only one that does not
    /// generate a key. It takes:
    ///
    ///   * an [`AuditedAddress`], which exists only if
    ///     [`audit_address`](crate::ceremony::audit_address) accepted a
    ///     [`CompositionArtifact`](crate::CompositionArtifact) -- so a
    ///     `CompositeSpend` cannot be built over a root whose two components
    ///     were not each proved possession of by every seat behind them and each
    ///     sealed under a commitment the reveal opens;
    ///   * the view private key, which derives the subaddress and the output's
    ///     shared secret and is not a cohort secret. It is CHECKED against the
    ///     address: `audit_address` established `D_i` for one `a`, and a
    ///     different `a` here would build a spend whose `common` term does not
    ///     belong to `D_i` -- unspendable, and not discovered until signing. It
    ///     is [`Error::ViewKeyMismatch`](crate::Error::ViewKeyMismatch) instead;
    ///   * `R`, the tx public key of the output being spent. It is meant to come
    ///     from an output observed on chain -- the depositor's `r` is the
    ///     depositor's, and unlike [`CompositeSpend::simulate`] nothing here
    ///     invents it -- but this function performs no chain lookup and accepts
    ///     any [`RistrettoPublic`]. "Observed" is the caller's obligation, not a
    ///     checked precondition.
    ///
    /// The two cohorts it carries hold NO SHARES. They are public roster,
    /// threshold and verification-share data, which is all the coordinator
    /// side of a signing session needs; a signer is built from each holder's
    /// own [`CohortShare::term`](crate::dkg::CohortShare::term). So
    /// [`CompositeSpend::onetime`], [`CompositeSpend::key_image_terms`] and
    /// [`quorum_signers`](crate::mlsag::quorum_signers) all answer
    /// [`Error::SharesNotHeld`](crate::Error::SharesNotHeld) on one of these.
    /// That is not a limitation being worked around; it is the difference
    /// between a dealing and a ceremony, made visible at the type's edge.
    pub fn from_ceremony(
        address: &AuditedAddress,
        view_private: &RistrettoPrivate,
        tx_public: &RistrettoPublic,
    ) -> Result<CompositeSpend> {
        let audited = address.root();
        let owners = distributed_cohort::<Owners>(audited.owner_reveal())?;
        let gates = distributed_cohort::<Gates>(audited.gate_reveal())?;

        let view = view_private.as_ref();
        let offset = Zeroizing::new(subaddress_offset(view, address.subaddress_index()));

        // The audited address was checked against ONE view key. Re-derive `D_i`
        // from the one supplied here and require it to be the same point; a
        // caller that passes a different key is otherwise handed a perfectly
        // well-formed `CompositeSpend` over a `common` term belonging to some
        // other address.
        if audited.root() + *offset * RISTRETTO_BASEPOINT_POINT
            != *address.spend_public().as_ref()
        {
            return Err(crate::Error::ViewKeyMismatch);
        }

        // Receiver-side derivation. The sender computed P as Hs(r*C_i)*G + D_i
        // with C_i = a*D_i; a*R = a*(r*D_i) = r*(a*D_i), so the two agree
        // without this side ever seeing `r`.
        let shared = hash_to_scalar(view * tx_public.as_ref());
        let target = RistrettoPublic::from(shared * RISTRETTO_BASEPOINT_POINT + address.spend_public().as_ref());

        Ok(CompositeSpend {
            owners,
            gates,
            provenance: Provenance::Ceremony(*audited.ceremony()),
            // Read off the AUDITED structures, so these are the keys `audit`
            // actually checked each commitment against -- equal by construction
            // to the `Parties` its caller supplied, since it could not have
            // returned otherwise. Copying them from the artifact's own
            // `SignedCommitment::signer` instead would be asking the artifact to
            // vouch for itself.
            endorsers: Some(Parties::new(
                *audited.owner_structure().identity(),
                *audited.gate_structure().identity(),
            )),
            view_private: *view_private,
            subaddress_index: address.subaddress_index(),
            spend_public: *address.spend_public(),
            tx_public: *tx_public,
            target,
            common: Zeroizing::new(shared + *offset),
        })
    }

    /// Which route this root reached a `CompositeSpend` by: the audited one, or
    /// [`CompositeSpend::simulate`].
    ///
    /// Not "ceremony or dealer" -- see [`Provenance`]. A dealer's artifact that
    /// passes [`audit_address`](crate::audit_address) reports
    /// [`Provenance::Ceremony`].
    pub fn provenance(&self) -> Provenance {
        self.provenance
    }

    /// The two organisations the audit behind this root was checked against.
    ///
    /// `None` for [`Provenance::Simulated`], which nobody endorsed.
    ///
    /// For a ceremony root these are the keys [`audit`](crate::audit) was GIVEN,
    /// not the ones the artifact names itself -- the audit compares the second
    /// against the first and refuses on a mismatch, so by the time this value
    /// exists they are the same. A release path compares them against the keys
    /// it obtained from the organisations; a spend audited under some other pair
    /// is otherwise indistinguishable from one audited under the real pair.
    pub fn endorsers(&self) -> Option<Parties> {
        self.endorsers
    }

    /// The OWNER cohort. Its roster lies in the [`Owners`] id band.
    pub fn owners(&self) -> &Cohort {
        &self.owners
    }

    /// The GATE cohort. Its roster lies in the [`Gates`] id band, which is
    /// disjoint from the owners', so no owner subset is a gate quorum.
    pub fn gates(&self) -> &Cohort {
        &self.gates
    }

    pub fn subaddress_index(&self) -> u64 {
        self.subaddress_index
    }

    /// `D_i`, the subaddress spend public key funds are paid to.
    pub fn spend_public(&self) -> &RistrettoPublic {
        &self.spend_public
    }

    /// `R`, the output's tx public key.
    pub fn tx_public(&self) -> &RistrettoPublic {
        &self.tx_public
    }

    /// `P`, the output's one-time (target) public key.
    pub fn target(&self) -> &RistrettoPublic {
        &self.target
    }

    /// The view private key `a`. Secret, but it authorises nothing on its own.
    pub fn view_private(&self) -> &RistrettoPrivate {
        &self.view_private
    }

    /// `Hs(a * R) + Hs(a || i)` -- the view-derived part of the one-time key.
    pub fn common(&self) -> &Scalar {
        &self.common
    }

    /// `B = B_owner + B_gate`, each half assembled from its own subset.
    pub fn composite_root(
        &self,
        owner_subset: &[u64],
        gate_subset: &[u64],
    ) -> Result<RistrettoPoint> {
        Ok(self.owners.public(owner_subset)? + self.gates.public(gate_subset)?)
    }

    /// The one-time private key `x` for a given pair of qualifying subsets.
    ///
    /// This MATERIALISES the scalar. It exists so the stock MobileCoin signer
    /// can be driven; a production signer must not call it.
    pub fn onetime(&self, owner_subset: &[u64], gate_subset: &[u64]) -> Result<Zeroizing<Scalar>> {
        let owner = self.owners.reconstruct(owner_subset)?;
        let gate = self.gates.reconstruct(gate_subset)?;
        Ok(Zeroizing::new(*self.common + *owner + *gate))
    }

    /// The per-participant key-image terms for a pair of qualifying subsets.
    ///
    /// Every term is a group element. No participant's scalar appears, and no
    /// subset of the terms sums to the one-time key.
    pub fn key_image_terms(
        &self,
        owner_subset: &[u64],
        gate_subset: &[u64],
    ) -> Result<KeyImageTerms> {
        // Against the ACTUAL output being spent, not against G -- the image is
        // only a nullifier because it is bound to this output.
        let hp = hash_to_point(&self.target);
        Ok(KeyImageTerms {
            view_term: *self.common * hp,
            owner_terms: self.owners.point_terms(owner_subset, &hp)?,
            gate_terms: self.gates.point_terms(gate_subset, &hp)?,
        })
    }

    /// The key image assembled from per-participant terms.
    pub fn key_image_from_shares(
        &self,
        owner_subset: &[u64],
        gate_subset: &[u64],
    ) -> Result<RistrettoPoint> {
        Ok(self.key_image_terms(owner_subset, gate_subset)?.sum())
    }

    /// What an OWNER quorum alone can assemble: the gate cohort's terms are
    /// simply absent from the sum.
    ///
    /// This is what a compromised operator majority reaches without the gates.
    /// It is a well-formed point and a useless one -- consensus checks the
    /// image against the ring, and this image belongs to no ring member.
    pub fn key_image_without_gates(&self, owner_subset: &[u64]) -> Result<RistrettoPoint> {
        let hp = hash_to_point(&self.target);
        let owners: RistrettoPoint = self
            .owners
            .point_terms(owner_subset, &hp)?
            .into_iter()
            .map(|(_, p)| p)
            .sum();
        Ok(*self.common * hp + owners)
    }
}

/// Redacted: `common` and the view key are secret, and the cohorts redact
/// themselves.
impl fmt::Debug for CompositeSpend {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CompositeSpend")
            .field("owners", &self.owners)
            .field("gates", &self.gates)
            .field("provenance", &self.provenance)
            .field("endorsers", &self.endorsers)
            .field("subaddress_index", &self.subaddress_index)
            .field("target", &self.target)
            .field("view_private", &"<redacted>")
            .field("common", &"<redacted>")
            .finish()
    }
}

/// A share-less [`Cohort`] over an audited reveal's public data.
///
/// The evaluation points are `1..=n`, matching the DKG that produced the
/// verification shares -- see [`dkg`](crate::dkg) on why they are not the ids.
fn distributed_cohort<C: ControlDomain>(reveal: &ComponentReveal) -> Result<Cohort> {
    Cohort::distributed(
        C::NAME,
        reveal.threshold(),
        reveal.roster(),
        &(1..=reveal.roster().len() as u64).collect::<Vec<_>>(),
        reveal.verification_shares(),
    )
}
