//! Ed25519 ORGANISATION identity keys: who produced a piece of the protocol.
//!
//! Nothing here is threshold material, and the separation is the whole point.
//! A threshold transcript is reproducible by anyone holding enough shares, so
//! it can say what a cohort's key IS and never who published it. An identity
//! signature is the other half: it says a named holder of a long-term key
//! endorsed these exact bytes, and it is not reproducible by the quorum it
//! would incriminate.
//!
//! # Why this lives in `two-cohort` and not in `crates/ceremony`
//!
//! It was written in `crates/ceremony/src/identity.rs` for identifiable abort,
//! where a signature over a round message is the only evidence a threshold
//! transcript cannot forge. [`ceremony`](crate::ceremony) now needs the same
//! notion for a different question -- which organisation sealed a component --
//! and `crates/ceremony` already depends on this crate, so importing upward
//! would be a cycle. The primitive therefore moved DOWN to the crate both can
//! reach, and `crates/ceremony`'s `identity` module re-exports these three
//! types rather than declaring a second identity notion beside them. One key
//! type, two uses: an organisation whose key signs a ceremony round message is
//! the same organisation whose key signs a commitment.
//!
//! # What a signature here does and does not say
//!
//! It says: the holder of this private key signed these bytes. It does NOT say
//! when, and it does not say the signer is a different organisation from the
//! other signer -- two "different" parties are two different keys, and whether
//! two keys are held by two organisations is a fact about the world. A funder
//! that checks a commitment against a key it obtained from the artifact rather
//! than from the organisation has checked nothing at all.
//!
//! # The key as a GROUP ELEMENT
//!
//! `IdentityPublic::edwards` and `IdentityKey::endorsement_secret` expose
//! the pair `(d, Id = d*B)` behind an Ed25519 key, which the signature API above
//! never needs. They exist for one caller:
//! [`ceremony::SeatEndorsement`](crate::ceremony::SeatEndorsement), which proves
//! knowledge of `d` AND of a DKG share in ONE sigma protocol under one
//! challenge. A signature cannot be half of such a proof -- it is a finished
//! object with its own internal challenge -- so the seat endorsement has to work
//! with the scalar directly.
//!
//! **The two groups are two groups, and the encodings differ -- but the bases
//! are the same numbers, and an earlier version of this comment leaned on the
//! difference to carry an argument it cannot carry.** `Id` is an Ed25519 point
//! encoded as a compressed Edwards `y`, and it is in the prime-order subgroup
//! generated by `B` for any key this module produces AND for any key that
//! survives `IdentityPublic::edwards`, which now checks. A verification share
//! `V = s*G` is a Ristretto point: an equivalence class, encoded by the
//! Ristretto encoding, and no Ristretto encoding is an Edwards encoding.
//!
//! What that does NOT give you is two unrelated generators.
//! `RISTRETTO_BASEPOINT_POINT`'s representative IS `ED25519_BASEPOINT_POINT`, so
//! `V`'s representative is `s*B` and `Id` is `d*B` over one numeric base. If the
//! two verification equations were ever collapsed into one with FIXED equal
//! weights -- a single `z` against `A + R + c*(Id + V)` -- knowledge of `d + s`
//! alone would satisfy it and the linkage would be gone. (A batch with
//! UNPREDICTABLE random coefficients would not have that problem; an earlier
//! version of this sentence said any batching would, which is too broad, and
//! adversarial review corrected it.) What actually prevents the collapse is that
//! there are TWO responses checked by TWO equations, never one; the separate
//! encodings are why nothing can be substituted across them by accident, not why
//! the composition is sound. What the shared scalar order `l` buys is that ONE
//! challenge is a valid challenge for both halves. See
//! `ceremony::SeatEndorsement` for the composition and its residual.

use curve25519_dalek::{
    constants::ED25519_BASEPOINT_POINT, edwards::CompressedEdwardsY, edwards::EdwardsPoint,
    scalar::Scalar, traits::IsIdentity,
};
use mc_crypto_keys::{Ed25519Pair, Ed25519Public, Ed25519Signature, Signer, Verifier};
use zeroize::Zeroizing;

/// An organisation's (or participant's) identity public key.
///
/// Newtype because the upstream key type carries neither `Debug` nor
/// `PartialEq`, and a roster -- and an audit error naming who signed -- wants
/// both.
#[derive(Clone, Copy)]
pub struct IdentityPublic(Ed25519Public);

impl IdentityPublic {
    pub fn as_bytes(&self) -> &[u8; 32] {
        self.0.as_ref()
    }

    /// `sig` is a signature by this key over `msg`.
    ///
    /// Returns a plain `bool` rather than a typed error because the two callers
    /// report the failure in their own vocabularies -- a participant id in
    /// `crates/ceremony`'s abort evidence, a cohort name in
    /// [`ceremony`](crate::ceremony)'s audit -- and a shared error type here
    /// would force one of them to translate.
    ///
    /// **Domain separation is the caller's.** This verifies over whatever bytes
    /// it is handed; every caller prefixes a tag naming the message type, so a
    /// signature over one kind of message cannot be replayed as another.
    pub fn verify(&self, msg: &[u8], sig: &IdentitySignature) -> bool {
        self.0.verify(msg, &Ed25519Signature::new(sig.0)).is_ok()
    }

    /// This key as the Edwards point `Id`, or `None` if the 32 bytes are not a
    /// point of the prime-order subgroup `<B>`.
    ///
    /// **The subgroup check is here, and an earlier version of this comment
    /// argued it was unnecessary. That argument was wrong and the omission was
    /// exploitable.**
    ///
    /// What it said: the caller verifies `z*B == A + c*Id`, the left side is in
    /// `<B>`, so the equation can only hold when `A + c*Id` is too; and the
    /// extraction argument that makes the proof sound (two accepting transcripts
    /// on one commitment give `Id = ((z - z')/(c - c'))*B`) already concludes
    /// `Id ∈ <B>`.
    ///
    /// Both halves are true and neither is a check. **`A` is the PROVER's
    /// choice** and nothing constrains it to `<B>`; the extraction argument
    /// needs TWO accepting transcripts on one commitment, which a verifier
    /// looking at one proof does not have. Concretely: with `Id` of order 8 and
    /// `A = k*B`, the equation `z*B == A + c*Id` holds with `z = k` for every
    /// challenge with `c ≡ 0 (mod 8)`. A prover holding no `d` at all -- and for
    /// a pure-torsion `Id` no `d` EXISTS -- grinds `k` until the challenge falls
    /// that way, expected 8 tries, and answers with `z = k`. The same grind with
    /// `Id = d*B + T` and a matching torsion component in `A` takes 2 tries and
    /// gives one secret eight distinct 32-byte "keys".
    /// `tests/seat_key_torsion.rs` performs both.
    ///
    /// This was a REGRESSION, not a pre-existing gap: the Ed25519 signature the
    /// seat endorsement replaced was verified by `verify_strict`, which refuses
    /// a small-order signer before it looks at the signature. Replacing the
    /// signature with a sigma proof dropped that refusal and wrote an argument
    /// where the check had been.
    ///
    /// **Two predicates, and NEITHER of them alone is enough.** The first draft
    /// of this fix used only `is_torsion_free`, and adversarial review caught
    /// that it admits the Edwards IDENTITY -- which is in the prime-order
    /// subgroup, so the predicate says yes. `Id = 0*B` has `d = 0`, a secret
    /// every reader of this comment holds:
    /// `z_d*B == A + c*Id` collapses to `z_d*B == A`, so any
    /// `A = k*B` with `z_d = k` verifies for EVERY challenge, with no grinding at
    /// all. That is strictly cheaper than the torsion forgery.
    ///
    /// The mirror predicate does not work either: `is_small_order` catches the
    /// identity and every pure-torsion point, and lets `d*B + T` through. So both
    /// are here. Together they say: this is a point of `<B>`, and it is not the
    /// one point of `<B>` whose discrete log is public.
    ///
    /// This is the same shape as
    /// [`CeremonyError::IdentityVerificationShare`](crate::ceremony::CeremonyError),
    /// which refuses `V = 0` for the identical reason on the share side. That one
    /// was already here; its twin was not, and the sigma protocol needed both.
    ///
    /// Cost is one scalar multiplication, on a path that already does two.
    ///
    /// `Option` rather than a panic because an `IdentityPublic` can arrive over
    /// the wire: it is a newtype over 32 bytes and
    /// [`ComponentClaim`](crate::ceremony::ComponentClaim) carries a vector of
    /// them. The caller treats `None` as "this endorsement does not verify",
    /// which is the accurate report -- there is no `d` with `d*B` equal to
    /// something that is not a point of `<B>`.
    ///
    /// **There are two guards and they are not redundant**, which is worth
    /// stating precisely rather than leaving a reader to assume one covers the
    /// other. `ComponentClaim::check_shape` refuses a torsion seat key earlier in
    /// [`audit`](crate::ceremony::audit) and with a typed error that names the
    /// seat and the bytes, so no audit reaches here with one; this guard is what
    /// refuses on the PUBLIC
    /// [`SeatEndorsement::verify`](crate::ceremony::SeatEndorsement::verify)
    /// path, which takes any signer an outside caller hands it and never sees
    /// `check_shape`.
    ///
    /// Delete `check_shape`'s and the forgery still dies here, as
    /// `SeatEndorsementInvalid` -- "the proof is bad" reported for "that is not a
    /// key". Delete this one and `check_shape` still refuses the claim, but the
    /// public entry point admits the forged proof. Measured: each deletion fails
    /// tests in `tests/seat_key_torsion.rs` and nothing else.
    pub(crate) fn edwards(&self) -> Option<EdwardsPoint> {
        let p = CompressedEdwardsY(*self.as_bytes()).decompress()?;
        if !p.is_torsion_free() || p.is_identity() {
            return None;
        }
        Some(p)
    }

    /// Which of [`edwards`](Self::edwards)' two refusals this key would hit, or
    /// `None` if it is usable.
    ///
    /// Split out from `edwards` because the audit reports the two differently --
    /// see `ceremony::CeremonyError::SeatKeyNotUsable` -- and because a funder
    /// reading "this is not a key" deserves to be told which way. `edwards`
    /// itself returns `Option` because its caller,
    /// [`SeatEndorsement::verify`](crate::ceremony::SeatEndorsement::verify),
    /// returns a `bool` and has nowhere to put a reason.
    ///
    /// **Public**, unlike `edwards`, for the reason
    /// `ceremony::seat_endorsement_challenge` is public: an independent
    /// implementation has to be able to apply the same admissibility rule, and a
    /// deployment collecting seat keys from four parties should be able to refuse
    /// an unusable one at collection time rather than at audit time. It exposes
    /// no secret and decides nothing -- [`audit`](crate::audit) applies it
    /// regardless of whether anyone called this.
    ///
    /// The two must stay in step: this function's `None` is exactly `edwards`'
    /// `Some`. `ceremony`'s `check_shape` calls THIS one, so a divergence would
    /// mean the audit refuses a key the proof path accepts or the reverse; the
    /// tests in `tests/seat_key_torsion.rs` assert both directions on the same
    /// values.
    pub fn unusable_reason(&self) -> Option<&'static str> {
        match CompressedEdwardsY(*self.as_bytes()).decompress() {
            None => Some("not a point on the curve"),
            Some(p) if p.is_identity() => {
                Some("the identity element, whose discrete log is 0 and is public")
            }
            Some(p) if !p.is_torsion_free() => {
                Some("outside the prime-order subgroup, so no secret exists behind it")
            }
            Some(_) => None,
        }
    }
}

impl From<Ed25519Public> for IdentityPublic {
    fn from(k: Ed25519Public) -> Self {
        IdentityPublic(k)
    }
}

impl PartialEq for IdentityPublic {
    fn eq(&self, other: &Self) -> bool {
        self.as_bytes() == other.as_bytes()
    }
}
impl Eq for IdentityPublic {}

impl std::fmt::Debug for IdentityPublic {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "IdentityPublic(")?;
        for b in &self.as_bytes()[..6] {
            write!(f, "{b:02x}")?;
        }
        write!(f, "..)")
    }
}

/// Full hex, because an audit rejection that names two keys is read by a human
/// deciding which organisation to go and talk to, and six bytes of prefix is
/// not enough to look a key up with.
impl std::fmt::Display for IdentityPublic {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for b in self.as_bytes() {
            write!(f, "{b:02x}")?;
        }
        Ok(())
    }
}

/// Detached Ed25519 signature, kept as bytes so the message types stay plain
/// data that can be compared, hashed and logged.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct IdentitySignature(pub [u8; 64]);

impl std::fmt::Debug for IdentitySignature {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "IdentitySignature(")?;
        for b in &self.0[..6] {
            write!(f, "{b:02x}")?;
        }
        write!(f, "..)")
    }
}

/// Signing side of an identity key.
pub struct IdentityKey {
    pair: Ed25519Pair,
}

impl IdentityKey {
    /// `seed` is the 32-byte Ed25519 private key (RFC 8032 secret key).
    pub fn from_seed(seed: &[u8; 32]) -> Self {
        let pair = Ed25519Pair::try_from(&seed[..]).expect("32 bytes is a valid Ed25519 seed");
        IdentityKey { pair }
    }

    /// A freshly drawn identity key.
    ///
    /// Every 32-byte string is a valid RFC 8032 secret key, so this is a draw
    /// and not a rejection loop.
    pub fn draw<R: rand_core::RngCore + rand_core::CryptoRng>(rng: &mut R) -> Self {
        let mut seed = [0u8; 32];
        rng.fill_bytes(&mut seed);
        IdentityKey::from_seed(&seed)
    }

    pub fn public(&self) -> IdentityPublic {
        IdentityPublic(self.pair.public_key())
    }

    /// Sign `msg`.
    ///
    /// **Domain separation is the caller's**, and it is not optional: this signs
    /// whatever bytes it is handed, so two message types that do not carry
    /// distinct tags are one message type as far as a verifier is concerned.
    /// The tags in use are `bridge/ceremony/round{1,2}/v1` in `crates/ceremony`
    /// and `two-cohort/composition/commit-signature/v1` in
    /// [`ceremony`](crate::ceremony), and each of those payload builders puts
    /// its tag first.
    pub fn sign(&self, msg: &[u8]) -> IdentitySignature {
        IdentitySignature(self.pair.sign(msg).to_bytes())
    }

    /// The scalar `d` with `d*B == Id`, this key's public point.
    ///
    /// RFC 8032 does not sign with the 32-byte secret key directly: it expands
    /// it, `SHA-512(sk) = d_bytes || prefix`, clamps `d_bytes`, and the public
    /// key IS `clamp(d_bytes)*B`. So this is the discrete log of the published
    /// key, and it is the only scalar that is -- it is not a second, parallel
    /// secret this module invented.
    ///
    /// It comes from [`ed25519_dalek::hazmat::ExpandedSecretKey`] rather than
    /// from a local SHA-512-and-clamp for a reason worth stating: that is the
    /// same expansion `IdentityKey::sign` performs one layer down, so the point
    /// this scalar opens is the key by construction. A hand-rolled expansion
    /// that clamped differently would still produce perfectly consistent proofs
    /// against a key nobody else recognises, and no signature check anywhere
    /// would notice.
    ///
    /// `pub(crate)`, and that is a narrowing rather than a boundary: whoever
    /// holds the seed holds `d`, and can compute it in three lines. What it
    /// prevents is a caller reaching for the raw scalar when it wanted
    /// [`sign`](IdentityKey::sign).
    pub(crate) fn endorsement_secret(&self) -> Zeroizing<Scalar> {
        let private = self.pair.private_key();
        let mut seed = Zeroizing::new([0u8; 32]);
        seed.copy_from_slice(private.as_ref());
        Zeroizing::new(ed25519_dalek::hazmat::ExpandedSecretKey::from(&*seed).scalar)
    }

    /// `Id = d*B`, this key's public point.
    ///
    /// Equal to `self.public().edwards().unwrap()`; computed from the SECRET so
    /// that the prover and the verifier reach the same point by two different
    /// routes, and a divergence between the expansion above and the signing key
    /// type would surface here rather than as an endorsement that silently never
    /// verifies.
    pub(crate) fn endorsement_point(&self) -> EdwardsPoint {
        *self.endorsement_secret() * ED25519_BASEPOINT_POINT
    }
}
