// Blake2b-256 known-answer tests.
//
// The expected values come from Python's hashlib (an independent, widely
// verified implementation), NOT from this Solidity code -- comparing an
// implementation against itself is the circularity that review has repeatedly
// caught in sibling work. The vectors are regenerated by the block in
// test/fixtures/blake2b.json's producing script and are plain Blake2b-256.
//
// The block-boundary cases matter more than they look: Blake2b's counter must
// carry the TRUE message length on the final block, not a padded multiple of
// 128, and 127/128/129 bytes are where that goes wrong.

import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import {
  Chain, selector, word, b32, dynBytes, test, assert, assertEq, summary,
  revertReason,
} from './harness.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const V = JSON.parse(readFileSync(join(HERE, 'fixtures', 'blake2b.json'), 'utf8'));

const chain = await Chain.create({ only: ['Blake2b256.sol'] });
const probe = await chain.deploy('Blake2b256Probe_DO_NOT_DEPLOY');

const hashOf = async (hexInput) => {
  const r = await chain.call(probe,
    selector('hash(bytes)') + word(32) + dynBytes(hexInput));
  assert(r.ok, `hash reverted: ${revertReason(r.ret)}`);
  return r.ret.slice(2, 66);
};

console.log('\nBlake2b256');

for (const name of ['empty', 'abc', '127B', '128B_exact_block', '129B_two_blocks', '300B']) {
  await test(`matches hashlib on ${name}`, async () => {
    assertEq(await hashOf(V[name].input), V[name].want, name);
  });
}

await test('the MobileCoin leaf domain tag is applied exactly', async () => {
  const r = await chain.call(probe,
    selector('hashLeaf(bytes32)') + b32(V.mc_leaf.txOutHash));
  assert(r.ok, `hashLeaf reverted: ${revertReason(r.ret)}`);
  assertEq(r.ret.slice(2, 66), V.mc_leaf.want, 'mc_tx_out_merkle_leaf');
});

await test('the MobileCoin node domain tag is applied exactly', async () => {
  const r = await chain.call(probe,
    selector('hashNodes(bytes32,bytes32)') + b32(V.mc_node.l) + b32(V.mc_node.r));
  assert(r.ok, `hashNodes reverted: ${revertReason(r.ret)}`);
  assertEq(r.ret.slice(2, 66), V.mc_node.want, 'mc_tx_out_merkle_node');
});

await test('a one-bit change in the input changes the digest', async () => {
  // Guards against an implementation that ignores its input, which would
  // otherwise satisfy any single fixed vector by construction.
  const a = await hashOf('00'.repeat(64));
  const b = await hashOf('00'.repeat(63) + '01');
  assert(a !== b, 'digest must depend on the input');
});

await test('leaf and node hashes of the same bytes differ', async () => {
  // Domain separation is the point of the tags: without it a node hash could
  // be presented as a leaf hash and the tree walk forged.
  const z = '0x' + '00'.repeat(32);
  const leaf = await chain.call(probe, selector('hashLeaf(bytes32)') + b32(z));
  const node = await chain.call(probe,
    selector('hashNodes(bytes32,bytes32)') + b32(z) + b32(z));
  assert(leaf.ret !== node.ret, 'domain tags must separate leaf from node');
});

summary();
