// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {IMobileCoinVerifier, VerifiedReturn} from "./IMobileCoinVerifier.sol";
import {ValidatorRegistry} from "./ValidatorRegistry.sol";
import {Ed25519} from "./Ed25519.sol";
import {Merlin} from "./Merlin.sol";
import {Blake2b256} from "./Blake2b256.sol";

/// Verifies that an eUSD output was paid to the bridge's return address and
/// finalized in a MobileCoin block, for the Ethereum side of the return leg.
///
/// The chain of reasoning the contract has to close, in order:
///
///   1. these signatures are over THIS block          (Merlin digest + Ed25519)
///   2. the signers are a real quorum                 (ValidatorRegistry)
///   3. this output is IN that block                  (membership proof)
///   4. this output is payable to US, in eUSD         (recipient + token)
///   5. it names a beneficiary, and only once ever    (memo + escrow replay set)
///
/// Any link left open is a way to take the escrow's USDC, so each is a
/// separate, individually testable step and none is inferred from another.
contract MobileCoinVerifier is IMobileCoinVerifier {
    /// Domain tag MobileCoin signs block digests under.
    bytes constant BLOCK_SIG_DOMAIN = "block-sig";

    /// Domain tag for this bridge's memo schema. Binding the memo to a domain
    /// is what stops a memo written for some other purpose -- or for a
    /// different deployment of this bridge -- from being replayed here as a
    /// redemption instruction.
    bytes32 public immutable memoDomain;

    ValidatorRegistry public immutable registry;

    /// The bridge's MobileCoin return subaddress spend public key, `D`.
    bytes32 public immutable returnSpendPublicKey;

    /// eUSD token id.
    uint64 public immutable eusdTokenId;

    struct Proof {
        // --- block header fields, in Digestible order ---
        bytes32 blockId;
        uint32 version;
        bytes32 parentId;
        uint64 index;
        uint64 cumulativeTxoCount;
        uint64 rootRangeFrom;
        uint64 rootRangeTo;
        bytes32 rootHash;
        bytes32 contentsHash;
        // --- quorum ---
        bytes32[] signerKeys;      // ordered by validator entity, ascending
        bytes32[2][] signatures;   // parallel to signerKeys
        // --- the output being redeemed ---
        bytes32 txOutPublicKey;
        bytes32 txOutTargetKey;
        /// The TxOut's own hash, as MobileCoin computes it. The Merkle leaf
        /// covers this, so it is what the membership walk starts from.
        bytes32 txOutHash;
        uint64 amount;
        uint64 tokenId;
        // --- memo, domain-bound ---
        bytes32 memoDomainTag;
        address beneficiary;
        // --- membership ---
        bytes32[] merklePath;
        uint64 merkleIndex;
    }

    error QuorumNotMet();
    error BadSignature(uint256 index);
    error SignerCountMismatch();
    error WrongTokenId(uint64 got, uint64 want);
    error WrongMemoDomain(bytes32 got, bytes32 want);
    error ZeroBeneficiary();
    error NotPayableToBridge();
    error MembershipFailed();

    constructor(
        ValidatorRegistry _registry,
        bytes32 _returnSpendPublicKey,
        uint64 _eusdTokenId,
        bytes32 _memoDomain
    ) {
        registry = _registry;
        returnSpendPublicKey = _returnSpendPublicKey;
        eusdTokenId = _eusdTokenId;
        memoDomain = _memoDomain;
    }

    /// The Digestible/Merlin digest MobileCoin validators sign for a block.
    ///
    /// Every validator signs THIS SAME value, which is what lets the digest be
    /// computed once for the whole quorum instead of once per signer.
    ///
    /// UNVALIDATED FIELD FRAMING. The sequence below is this contract's
    /// hypothesis about MobileCoin's Digestible encoding, not a transcription
    /// of it. Digestible wraps aggregates in their own framing rather than
    /// emitting a flat list of labelled fields, so this is very likely wrong
    /// in detail. It is only correct if it reproduces the digest a real
    /// MobileCoin node produces, byte for byte -- which is what the fixture
    /// test in test/verifier.mjs decides. Do NOT rely on this function until
    /// that test passes against a fixture generated by the Rust side.
    function blockDigest(Proof memory p) public pure returns (bytes32) {
        Merlin.Transcript memory t = Merlin.init(BLOCK_SIG_DOMAIN);
        Merlin.appendMessage(t, "id", abi.encodePacked(p.blockId));
        Merlin.appendU64(t, "version", uint64(p.version));
        Merlin.appendMessage(t, "parent_id", abi.encodePacked(p.parentId));
        Merlin.appendU64(t, "index", p.index);
        Merlin.appendU64(t, "cumulative_txo_count", p.cumulativeTxoCount);
        Merlin.appendU64(t, "from", p.rootRangeFrom);
        Merlin.appendU64(t, "to", p.rootRangeTo);
        Merlin.appendMessage(t, "hash", abi.encodePacked(p.rootHash));
        Merlin.appendMessage(t, "contents_hash", abi.encodePacked(p.contentsHash));
        return bytes32(Merlin.challengeBytes(t, "block-digest", 32));
    }

    /// Step 1 and 2: a real quorum signed this block.
    function verifyQuorum(Proof memory p) public view returns (bytes32 digest) {
        if (p.signerKeys.length != p.signatures.length) {
            revert SignerCountMismatch();
        }
        // Entity-scoped and height-scoped. See ValidatorRegistry for why
        // counting keys instead of entities would be a forgery.
        if (!registry.isQuorum(p.signerKeys, p.index)) revert QuorumNotMet();

        digest = blockDigest(p);
        bytes memory msg32 = abi.encodePacked(digest);
        for (uint256 i = 0; i < p.signerKeys.length; i++) {
            if (!Ed25519.verify(p.signatures[i], p.signerKeys[i], msg32)) {
                revert BadSignature(i);
            }
        }
    }

    /// Step 3: this output is in that block.
    ///
    /// MobileCoin's TxOut Merkle tree hashes with Blake2b-256 under domain
    /// tags, which Ethereum exposes only as the compression function F at
    /// precompile 0x09 (EIP-152), so `Blake2b256` reconstructs the whole hash.
    /// `txOutHash` is the TxOut's own hash as MobileCoin computes it -- the
    /// leaf hashes THAT, not the raw key material.
    function verifyMembership(Proof memory p) public view returns (bool) {
        bytes32 node = Blake2b256.hashLeaf(p.txOutHash);
        uint64 idx = p.merkleIndex;
        for (uint256 i = 0; i < p.merklePath.length; i++) {
            node = (idx & 1 == 0)
                ? Blake2b256.hashNodes(node, p.merklePath[i])
                : Blake2b256.hashNodes(p.merklePath[i], node);
            idx >>= 1;
        }
        return node == p.rootHash;
    }

    /// Steps 4 and 5, then hand the escrow a value it can act on.
    function verifyReturn(bytes calldata proof)
        external
        view
        returns (VerifiedReturn memory)
    {
        Proof memory p = abi.decode(proof, (Proof));

        verifyQuorum(p);

        if (!verifyMembership(p)) revert MembershipFailed();

        if (p.tokenId != eusdTokenId) {
            revert WrongTokenId(p.tokenId, eusdTokenId);
        }
        if (p.memoDomainTag != memoDomain) {
            revert WrongMemoDomain(p.memoDomainTag, memoDomain);
        }
        if (p.beneficiary == address(0)) revert ZeroBeneficiary();

        // The recipient check. See the note on `_payableToBridge`: this is the
        // one link in the chain that is NOT yet closed on-chain.
        if (!_payableToBridge(p)) revert NotPayableToBridge();

        return VerifiedReturn({
            outputPublicKey: p.txOutPublicKey,
            beneficiary: p.beneficiary,
            amount: p.amount,
            tokenId: p.tokenId,
            blockIndex: p.index
        });
    }

    // -------------------------------------------------------------- internal

    /// UNIMPLEMENTED ON-CHAIN, AND DELIBERATELY LOUD ABOUT IT.
    ///
    /// The correct check is `target_key == Hs(a * R) * G + D`, where `a` is the
    /// return address's published view private key, `R` is the output's public
    /// key and `D` is `returnSpendPublicKey`. That is the check that proves the
    /// output is payable to the bridge; a view-key *match* is NOT sufficient,
    /// and MobileCoin's own light-client relayer has a latent defect of exactly
    /// that shape -- it classifies burns with a check that never reads
    /// `target_key`.
    ///
    /// Implementing it requires Ristretto255 point decompression and scalar
    /// multiplication in Solidity. MobileCoin uses Ristretto, not raw Ed25519,
    /// so `Ed25519.decompress` is NOT interchangeable here and reusing it would
    /// be wrong in a way that still passes casual tests.
    ///
    /// Until that library exists this contract MUST NOT hold live funds. It is
    /// left reverting rather than returning true so that no deployment can
    /// accidentally treat the gap as closed.
    function _payableToBridge(Proof memory) internal pure returns (bool) {
        revert("recipient check requires Ristretto255; see _payableToBridge");
    }

}
